### ISSUE TITLE
Rename part of hadar

### ISSUE THREAD

**Issue by FrancoisJ** [hadar-simulator/hadar#45]
Some names sound wrong for many persons. Need to rename:

- [ ] aggregator : This part will take result from solver and facilitate computation on data for user.
- [ ] solver : This part will build optimization equation and send it to or-tool
- [ ] generator: this part will create a study from timeline generated by user.
- [ ] border : Item to represent transfert capacity and cost between to node.

According to these description, please comment this issue with new idea.
If you like a proposition add a positive emoji on this comment.

**Comment by FrancoisJ** [comment]
aggregator -> **postprocessing**

**Comment by FrancoisJ** [comment]
border --> **link**

**Comment by PPlessiez** [comment]
solver -> **problem builder**

**Comment by PPlessiez** [comment]
generator -> **scenario builder**

**Comment by sgatto** [comment]
maybe
generator -> studygenerator

**Comment by sgatto** [comment]
> 
> 
> aggregator -> **postprocessing**

don't know... dataaggregator is not so bad either

**Comment by FrancoisJ** [comment]
aggragator --> analyzer

**Comment by FrancoisJ** [comment]
> solver -> **problem builder**

For me, builder term means a very specifics constructor pattern. I would like to keep for this purpose and avoid confusion.

**Comment by sgatto** [comment]
**solver**:
it needs another name,

**modeler** is not a good one since the module that is called **solver** contains "a modeler"+"a solver"

**simulator** sounds very general

**calculator** ???

**optimizer**

**Comment by FrancoisJ** [comment]
> solver --> optimizer

**Comment by klorel** [comment]
Hi guys!
aggregator --> analyzer --> data manager ?
border --> link --> transmission device ? 
solver --> optimizer --> optimal power flow manager ? 

Could you describe more precisely what the generator (or scenario builder) does ?

**Comment by FrancoisJ** [comment]
Hi everyone,

Generator is like optional toolbox to help user to generate a study to compute.
For example with generator, user can create pipeline to transform data like generating many fault scenarios for production or generating some stochastic load behavior.

Generator can also gathering data and sampling to generate other monte-carlo scenario.

People can develop from scratch algorithm to handle their scenarios or they can use hadar generator part.

**Comment by klorel** [comment]
Thanks François!
So with this module, the user can design the workflow related to his study so ... workflow manager/designer  ? 
++
Manuel

**Comment by FrancoisJ** [comment]
I like workflow
generator -> workflow

**Comment by FrancoisJ** [comment]
Thanks for your participation, winners are:
- generator --> workflow
- solver --> optimizer
- aggregator --> analyzer
- border --> link
